### ISSUE TITLE
Error during creation patch baseline

### ISSUE THREAD

**Issue by karimooo** [jparnaudeau/terraform-aws-ssm-patch-management#4]
Hello,
i'm facing an issue during creation of the patchbaseline with this error : 
Error: Error running command '      module/register_default_patch_baseline/register-default-patch-baseline.py register pb-01ec5ab46be344feb CENTOS
': exit status 126. Output: /bin/sh: module/register_default_patch_baseline/register-default-patch-baseline.py: Permission denied
Error: Error running command '      module/patch_baseline/register-patch-baseline-for-patch-group.sh pb-01ec5ab46be344feb dev
': exit status 126. Output: /bin/sh: module/patch_baseline/register-patch-baseline-for-patch-group.sh: Permission denied
Error: Error running command '      module/patch_baseline/register-patch-baseline-for-patch-group.sh pb-01ec5ab46be344feb dev
': exit status 126. Output: /bin/sh: module/patch_baseline/register-patch-baseline-for-patch-group.sh: Permission denied

This is the final step to apply this module on my architecture .
Thanks a lot for your help.
Regards
Karim

![image](https://user-images.githubusercontent.com/44767305/123058495-2bd36300-d409-11eb-8df6-361a4f4c9f33.png)

**Comment by jparnaudeau** [comment]
Hi,

Can you check that you have python3 correctly installed on your workstation ? Can you check that the  module/register_default_patch_baseline/register-default-patch-baseline.py have the correct permissions ?

**Comment by jparnaudeau** [comment]
For your information : i have published a new version 1.0.3 that should fix the error related to the use of "register-patch-baseline-for-patch-group.sh" when calling the **patch_baseline** submodule. The inital bug have been fixed in the provider, so we can use the official resource aws_ssm_patch_group.

**Comment by karimooo** [comment]
Hi,
Thanks a lot for your quick feedback.

Yes permissions an py script are ok 
![image](https://user-images.githubusercontent.com/44767305/123093119-90071e80-d42b-11eb-83b6-831ccc6505af.png)
I can't check the version on python cause not admin on gitlabrunner , i launch the terraform via gitlabci pipeline
On my workstation i'm done with python version
![image](https://user-images.githubusercontent.com/44767305/123093507-14f23800-d42c-11eb-9aad-5b1e14ee0f7c.png)

**Comment by jparnaudeau** [comment]
Hi karimoo,
Hmmm i think it's a problem in your runner, maybe it does not allow the execution of the python script ?

Unfortunately,  the aws terraform provider does not provide a way to make the "defaut registration" of a patch baseline. I have coded this ugly "null_resource" to do it but it's not very the good approach.

I advice you to pass 

`set_default_patch_baseline = false`

and make the call to the aws api by yourself : 

`response = client.register_default_patch_baseline(BaselineId=baselineId)`
